In [3]:
# 🔢 Day 4 - NumPy Basics

import numpy as np

# 1. Creating a NumPy Array
numbers = np.array([10, 20, 30, 40, 50])

print("1️⃣ NumPy Array:")
print(numbers)


# 2. Array Properties
print("\n2️⃣ Array Properties:")
print("Shape:", numbers.shape)
print("Dimensions:", numbers.ndim)
print("Data Type:", numbers.dtype)
print("Size:", numbers.size)


# 3. Mathematical Operations
print("\n3️⃣ Mathematical Operations:")
print("Add 10:", numbers + 10)
print("Multiply by 2:", numbers * 2)


# 4. Statistical Operations
print("\n4️⃣ Statistical Operations:")
print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))


# 5. 2D NumPy Array
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("\n5️⃣ 2D Array:")
print(matrix)

print("\nShape:", matrix.shape)
print("Dimensions:", matrix.ndim)


# 6. Indexing
print("\n6️⃣ Indexing:")
print("First Element:", numbers[0])
print("Last Element:", numbers[-1])

1️⃣ NumPy Array:
[10 20 30 40 50]

2️⃣ Array Properties:
Shape: (5,)
Dimensions: 1
Data Type: int64
Size: 5

3️⃣ Mathematical Operations:
Add 10: [20 30 40 50 60]
Multiply by 2: [ 20  40  60  80 100]

4️⃣ Statistical Operations:
Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10

5️⃣ 2D Array:
[[10 20 30]
 [40 50 60]]

Shape: (2, 3)
Dimensions: 2

6️⃣ Indexing:
First Element: 10
Last Element: 50
